//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public int BankAccountId { get; set; }
        public string InterbankCode { get; set; }
        public string CardNumber { get; set; }
        public string AccountType { get; set; }
        public string CardType { get; set; }
        public string BankName { get; set; }
        public Nullable<int> Customer_CustomerId { get; set; }
        public Nullable<int> CreditRequestId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
