//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.CreditRequestAsTransferAccount = new HashSet<CreditRequest>();
            this.CreditRequestAsDirectDebitAccount = new HashSet<CreditRequest>();
        }
    
        public int BankAccountId { get; set; }
        public string InterbankCode { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> CardType { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> BankBankId { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditRequest> CreditRequestAsTransferAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditRequest> CreditRequestAsDirectDebitAccount { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
