//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public int BankAccountId { get; set; }
        public string InterbankCode { get; set; }
        public string CardNumber { get; set; }
        public string AccountType { get; set; }
        public string CardType { get; set; }
        public string BankName { get; set; }
        public Nullable<int> Customer_CustormerId { get; set; }
        public Nullable<int> CreditRequestId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
