//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRequestCreditPolicy
    {
        public int CreditRequestCreditPolicyId { get; set; }
        public Nullable<int> CreditRequestId { get; set; }
        public Nullable<int> CreditPolicyId { get; set; }
    
        public virtual CreditPolicy CreditPolicy { get; set; }
        public virtual CreditRequests CreditRequests { get; set; }
    }
}
