//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditOpeningForm
    {
        public Nullable<double> Amount { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<double> AmountRequested { get; set; }
        public int PaymentsInterval { get; set; }
        public Nullable<decimal> PaymentsAmount { get; set; }
        public int CreditRequestId { get; set; }
    }
}
