//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditConditionCreditRequest
    {
        public int CreditConditionIdRequest { get; set; }
        public Nullable<int> CreditCondition_CreditConditionId { get; set; }
        public Nullable<int> CreditRequests_CreditRequestId { get; set; }
    }
}
