//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditPolicy
    {
        public int CreditPolicyId { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    }
}
