//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditOpeningForm
    {
        public Nullable<double> Amount { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<double> AmountRequested { get; set; }
        public int PaymentsInterval { get; set; }
        public Nullable<decimal> PaymentsAmount { get; set; }
        public int CreditRequestId { get; set; }
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string SecondSurname { get; set; }
        public Nullable<int> TimePeriod { get; set; }
    }
}
