//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerAddresses()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int CustomerAddressId { get; set; }
        public string ExternalNumber { get; set; }
        public string InternalNumber { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> TypeAddressId { get; set; }
        public Nullable<int> LocalizationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        public virtual TypeAddress TypeAddress { get; set; }
        public virtual Localization Localization { get; set; }
    }
}
