//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int CustomerAddressId { get; set; }
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public string ExternalNumber { get; set; }
        public string InternalNumber { get; set; }
        public Nullable<int> CustormerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
