//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public int CreditRequestId { get; set; }
        public Nullable<int> DocumentType { get; set; }
    
        public virtual CreditRequest CreditRequest { get; set; }

    }
}
