//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomicilePaymentsAuth
    {
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string PhoneNumber1 { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string InterbankCode { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public string FileNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> TimePeriod { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeFirstSurname { get; set; }
        public string EmployeeSecondSurname { get; set; }
        public int CreditRequestId { get; set; }
    }
}
