//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomicilePaymentsAuth
    {
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string PhoneNumber1 { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string InterbankCode { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public string FileNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> TimePeriod { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeFirstSurname { get; set; }
        public string EmployeeSecondSurname { get; set; }
        public int CreditRequestId { get; set; }
        public int PaymentsInterval { get; set; }
        public string SecondSurname { get; set; }
    }
}
