//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public string FileNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Amount { get; set; }
        public Nullable<int> CreditRequestId { get; set; }
        public int CreditRequests_CreditRequestId { get; set; }
    
        public virtual CreditRequests CreditRequests { get; set; }
    }
}
