//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCenters
    {
        public int WorkCenterId { get; set; }
        public string CenterName { get; set; }
        public string Street { get; set; }
        public string Colony { get; set; }
        public Nullable<int> InnerNumber { get; set; }
        public Nullable<int> OutsideNumber { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Customer_CustomerId { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
